arch:
- aarch64
- amd64
- armv7
- armhf
codenotary: codenotary@degatano.com
description: AMR2MQTT for Home Assistant
image: ghcr.io/mdegat01/amr2mqtt/{arch}
init: false
map:
- ssl
name: AMR2MQTT
options:
  meters: []
  mqtt: {}
schema:
  home_assistant_discovery_enabled: bool?
  home_assistant_discovery_prefix: match(^[^+#]{1,65535}$)?
  last_seen: list(ISO_8601|ISO_8601_local|epoch)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  meters:
  - id: int
    manufacturer: str?
    model: str?
    multiplier: float(0,)?
    name: str?
    precision: int(0,)?
    protocol: list(idm|netidm|r900|scm|scm+)
    type: list(gas|water|energy)?
    unit_of_measurement: str?
  mqtt:
    base_topic: match(^[^+#]{1,65535}$)?
    ca: str?
    cert: str?
    client_id: str?
    host: str?
    key: str?
    password: password?
    port: port?
    username: str?
  rtlamr_symbol_length: list(8|32|40|48|56|64|72|80|88|96)?
services:
- mqtt:want
slug: amr2mqtt
uart: true
udev: true
url: https://github.com/mdegat01/addon-amr2mqtt
usb: true
version: 2.1.2
