arch:
- aarch64
- amd64
- armv7
- armhf
description: AMR2MQTT for Home Assistant
image: ghcr.io/mdegat01/amr2mqtt/{arch}
map:
- ssl
name: AMR2MQTT
options:
  message_types:
  - scm
  - idm
  mqtt: {}
  reading_multiplier: 1.0
  watched_meters: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  message_types:
  - list(idm|r900|scm|scm+)
  mqtt:
    base_topic: str?
    ca: str?
    cert: str?
    client_id: str?
    host: str?
    key: str?
    password: password?
    port: port?
    username: str?
  reading_multiplier: float(0,)?
  readings_per_hour: int(1,)?
  watched_meters:
  - int
services:
- mqtt:want
slug: amr2mqtt
uart: true
udev: true
url: https://github.com/mdegat01/addon-amr2mqtt
usb: true
version: efe8c6e
